services:
  spring-app:
    container_name: goldx
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - postgres
#      - rabbitmq
      - redis

  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${DB_NAME} # DB 이름
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # 데이터 영속성 유지

#  rabbitmq:
#    image: rabbitmq:management # 관리 UI가 포함된 RabbitMQ 이미지 사용
#    container_name: rabbitmq-container
#    environment:
#      RABBITMQ_DEFAULT_PASS: secret
#      RABBITMQ_DEFAULT_USER: myuser
#    ports:
#      - "5672:5672" # AMQP 프로토콜 포트
#      - "15672:15672" # 관리 UI 포트

  redis:
    image: redis:7.2.5
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # 데이터 영속성을 위한 옵션 추가

volumes:
  postgres-data:
