spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goldxdb
    username: goldx
    password: goldx1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379