name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "ci/cd" ]
  pull_request:
    branches: [ "ci/cd" ]

jobs:
  deploy:
    name: Deploy Application with Docker
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Login to Docker 
      - name: Login to Docker Hub
        uses: docke /login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 3. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          # Docker 이미지 이름과 태그 설정
          IMAGE_NAME=seyoungkwon29/goldx
          TAG=latest

          # Docker 이미지 빌드
          docker build -t $IMAGE_NAME:$TAG .

          # Docker Hub에 이미지 푸시
          docker push $IMAGE_NAME:$TAG
          
      # 4. Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ scretes.EC2_HOST }}
        run: |
          ssh $EC2_USER@EC2_HOST << 'EOF'
            set -e
            
            # Stop existing containers
            docker stop nginx-container || true
            docker rm nginx-container || true

            # Pull the latest Docker Image
            docker pull seyoungkwon29/nginx:latest
            EOF
            
            # Run the Docker container
            docker run --name nginx-container -p 80:80 -d seyoungkwon29/nginx:latest
